CREATE TABLE
IF NOT EXISTS t_users (
  id BIGINT UNIQUE NOT NULL AUTO_INCREMENT,
  username VARCHAR (100) NOT NULL,
  password VARCHAR (50) NOT NULL,
  time TIMESTAMP (0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);